import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* It is possible have a clientComponent like "ReactQueryProvider" and renders a "serverComponent" inside it only if the serverComponent were passed like prop children to this clientComponent like in this case here. This is a hack of the Next.js that it is important to know. */}
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Toaster position="top-center" richColors /> {/* makes the user message appears on the top of the screen */}
      </body>
    </html>
  );
}
